@tool
extends EditorPlugin

func _enter_tree():
	# Initialization of the plugin goes here.
	pass

func _build():
	var path: String = "res://nova/sources/gdscript/runtime/"
	var output_path: String = "res://nova/sources/gdscript/runtime_block.gd"

	print_verbose("Fetching compatible mapping from runtime sources...")
	
	var dir = DirAccess.open(path)
	if not dir:
		printerr("Failed to open directory:", path)
		return false
	
	var files = []
	dir.list_dir_begin()
	while true:
		var file = dir.get_next()
		if file == "":
			break
		if file.get_extension() == "gd":
			files.append(file)

	dir.list_dir_end()

	var func_mappings = {}
	var var_mappings = {}

	var class_regex = RegEx.new()
	class_regex.compile("class_name ([A-Za-z0-9_]+)")

	var var_regex = RegEx.new()
	var_regex.compile("#@export\nstatic var ([A-Za-z0-9_]+)")

	var func_regex = RegEx.new()
	func_regex.compile("#@export\nstatic func ([A-Za-z0-9_]+)")

	var module_list = []
	
	for file in files:
		var text = FileAccess.open(path + file, FileAccess.READ).get_as_text()
		var cls_name = class_regex.search(text)
		if not cls_name:
			continue

		var cls = cls_name.get_string(1)
		
		var exports = []
		var export = var_regex.search(text)
		while export:
			var name = export.get_string(1)
			exports.append(name)
			export = var_regex.search(text, export.get_end())
		if exports.size() > 0:
			var_mappings[cls] = exports

		exports = []
		export = func_regex.search(text)
		while export:
			var name = export.get_string(1)
			var start = export.get_end()
			var end = text.find(")", start)
			var signature = text.substr(start, end - start)
			signature = signature.lstrip("(").rstrip(")")
			exports.append({"name": name, "signature": signature})
			export = func_regex.search(text, end)
		if exports.size() > 0:
			func_mappings[cls] = exports

		if cls in func_mappings or cls in var_mappings:
			module_list.append(cls)

	var output = FileAccess.open(output_path, FileAccess.WRITE)
	if not output:
		printerr("Failed to open file for writing:", output_path)
		return false
	
	output.store_string("# This file is generated by the Nova Engine. Do not modify.\n\n")
	output.store_string("class_name RuntimeBlock extends BaseBlock\n\n")
	for cls in module_list:
		output.store_string("## " + cls + "\n")

		if cls in var_mappings:
			for export in var_mappings[cls]:
				output.store_string("static var " + export + ":\n\t")
				output.store_string("get: return " + cls + "." + export + "\n\t")
				output.store_string("set(value): " + cls + "." + export + " = value\n")

		if cls in func_mappings:
			for export in func_mappings[cls]:
				output.store_string("func " + export["name"] + "(" + export["signature"] + "):\n\t")
				output.store_string(cls + "." + export["name"] + "(")
				var params = export["signature"].split(", ")
				var param_list = []
				for param in params:
					var parts = param.split(":")
					if parts.size() > 1:
						param_list.append(parts[0])
					else:
						parts = param.split("=")
						if parts.size() > 1:
							param_list.append(parts[0])
						else:
							param_list.append(param)
				output.store_string(", ".join(param_list))
				output.store_string(")\n")

		output.store_string("\n")
	
	return true

func _exit_tree():
	# Clean-up of the plugin goes here.
	pass
