# This file is generated by the Nova Engine. Do not modify.

class_name RuntimeBlock extends BaseBlock

## BuiltIn
static var o:
	get: return BuiltIn.o
	set(value): BuiltIn.o = value
static var c:
	get: return BuiltIn.c
	set(value): BuiltIn.c = value

## DialogueBox
func set_box(pos_name="bottom"):
	DialogueBox.set_box(pos_name)

## Graphics
func move(obj: Variant, coord: Variant, scale=null, angle=null):
	Graphics.move(obj, coord, scale, angle)
func tint(obj, color):
	Graphics.tint(obj, color)
func show(obj, image_path, coord=null, color=null):
	Graphics.show(obj, image_path, coord, color)
func hide(obj):
	Graphics.hide(obj)

