# This file is generated by the Nova Engine. Do not modify.

class_name RuntimeBlock extends RefCounted

## BuiltIn
static var o:
	get: return BuiltIn.o
	set(value): BuiltIn.o = value
static var c:
	get: return BuiltIn.c
	set(value): BuiltIn.c = value
func pop_prefix(s: String, prefix: String, sep_len: int=0):
	BuiltIn.pop_prefix(s, prefix, sep_len)

## DialogueBox
func set_box(pos_name="bottom"):
	DialogueBox.set_box(pos_name)

## Graphics
func move(obj: Variant, coord: Variant, scale=null, angle=null):
	Graphics.move(obj, coord, scale, angle)
func tint(obj, color):
	Graphics.tint(obj, color)
func show(obj, image_path, coord=null, color=null):
	Graphics.show(obj, image_path, coord, color)
func hide(obj):
	Graphics.hide(obj)

## ScriptLoader
func action_new_file(filename: String):
	ScriptLoader.action_new_file(filename)
func label(name: String, display_name=null):
	ScriptLoader.label(name, display_name)
func jump_to(dest: String):
	ScriptLoader.jump_to(dest)
func branch(branches: Array):
	ScriptLoader.branch(branches)
func is_chapter():
	ScriptLoader.is_chapter()
func is_start():
	ScriptLoader.is_start()
func is_unlocked_start():
	ScriptLoader.is_unlocked_start()
func is_debug():
	ScriptLoader.is_debug()
func is_end(name=null):
	ScriptLoader.is_end(name)

