# This file is generated by the Nova Engine. Do not modify.

class_name RuntimeBlock extends BaseBlock

## DialogueBox
static func set_box(pos_name="bottom"):
	DialogueBox.set_box(pos_name)

## Graphics
static func move(obj: Variant, coord: Variant, scale=null, angle=null):
	Graphics.move(obj, coord, scale, angle)
static func tint(obj, color):
	Graphics.tint(obj, color)
static func show(obj, image_path, coord=null, color=null):
	Graphics.show(obj, image_path, coord, color)
static func hide(obj):
	Graphics.hide(obj)

